services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - MONGO_CONNECTION_STRING=mongodb://root:example@mongo:27017/
    volumes:
      - ./naver_smart_store_rag_chatbot:/app/naver_smart_store_rag_chatbot
    command: uvicorn naver_smart_store_rag_chatbot.main:app --host=0.0.0.0 --port=8080 --reload
    depends_on:
      chroma:
        condition: service_healthy
      mongo:
        condition: service_healthy
  chroma:
    image: ghcr.io/chroma-core/chroma:0.6.0
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./chroma:/chroma/chroma
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat" ]
      interval: 5s
      timeout: 5s
      retries: 3
  mongo:
    image: mongo:8.0.4
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "\"db.adminCommand('ping')\"" ]
      interval: 5s
      timeout: 5s
      retries: 5
