services:
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./naver_smart_store_rag_chatbot:/app/naver_smart_store_rag_chatbot
    command: uvicorn naver_smart_store_rag_chatbot.main:app --host=0.0.0.0 --port=8080 --reload
