FROM node:22-alpine

WORKDIR /app

COPY chatbot_ui/package*.json ./

RUN npm install

COPY chatbot_ui/ ./

EXPOSE 5173

ARG VITE_API_PATH
ENV VITE_API_PATH=${VITE_API_PATH}

CMD ["npm", "run", "dev", "--", "--host"]
